@startmindmap
caption Draft
title Application modernization

+[#Orange] Modernization
++ Legacy
+++_ No automated tests
+++_ Long-lived codebase
-- Embrace change
---_ High TTM
---_ High default rate
@endmindmap


